language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: LnsJc6dD/szxSCsg1q81t3oLxa08B/3w64xAk0izVkGhjklMCXtiqdiGpkDqorWtnOVGeY2UO8ZxyO5wteZ9eh0IqJg8kK8nTwIUAHT5lOI3ZGfoQS9sA5EPq7z0vFFgRTjWiqbV7Mzc/iJl4Q43w3Y4Iy8TSpkyDw5ihSkOKAov0kFqblQJQu0t1aqd+oVw1lZLW3lOxZZ2mVMvn3VNQ6m5VPxuYQxlOYU+IyR7DGCbqbiT9XrMe60Dd7PgznHSgjI9SuryOJImhE1wcsT52ckNpab4UDFY/yzcRJ5qHC7aDneCj/6Y3o3rZ8UD8JydZ92U1wyNmYUKgohLAcqDmo/1XqPg2DyNCRwZIHINcKNBA4BaDPwAIDuwECjGUDya06EUvwrhD6BkynuARpgLTsAmXRbZQEGsBNA4y6mc89aKvXSBkDV2bT5+tJTHTtgVwOTD6/YfySCbgaj9XbEjivER667cM7+wUNFgOVT2csN4O1i1gijx+fq24RCGJ0KrrvHIHPc7HfOFaPcYvUVTfUTzEM8eFDwQ1nxWAZdboAtPxHffB6gwY3r5uWIenIlCyYxYm1IoncPpr4T+Tb4IYyuIovMKObj6KwqeQoT6B3ciPVMCEDU4RKkxoEAMLPc0pVFGbkN0PwHmPnt/8vsi2PrFs6/1s7F+6QAOPRyTibQ=
  app: whispering-thicket-40897
  on:
    repo: rohinieravi/blog-app-mongoose-challenge-solution
